dockerauth-config:
  build: .
  restart: always
dockerauth:
  image: monami0ya/docker_auth
  ports:
    - "5001:5001"
  volumes_from:
    - dockerauth-config
  command: /config/auth_config.yml
  restart: always
registry:
  image: registry:latest
  ports:
    - "5000:5000"
  volumes_from:
    - dockerauth-config
  restart: always
  environment:
    - REGISTRY_STORAGE=azure
    - REGISTRY_STORAGE_AZURE_ACCOUNTNAME="<<EDITME>>"
    - REGISTRY_STORAGE_AZURE_ACCOUNTKEY="<<EDITME>>"
    - REGISTRY_STORAGE_AZURE_CONTAINER="registry"
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://localhost:5001/auth
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem
